import {test} from 'node:test';import assert from 'node:assert/strict';import {createHandler,hash} from './auth.mjs';
const app=createHandler({'/index.html':{body:'PRIVATE TREE',type:'text/html'},'/people.js':{body:'PRIVATE NAMES',type:'text/javascript'}}),origin='https://family.example';
const env={FAMILY_PASSWORD_HASH:await hash('test-password-only'),FAMILY_SESSION_KEY:'test-signing-key-for-unit-tests-only'};
const request=(path,opts={})=>new Request(origin+path,opts);
function login(password,extra={}){return app.fetch(request('/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/x-www-form-urlencoded','cf-connecting-ip':crypto.randomUUID(),...extra},body:new URLSearchParams({password,remember:'yes'})}),env)}
test('anonymous requests cannot retrieve any family assets or alternate paths',async()=>{for(const path of ['/','/people.js','/index.html','/people.js?download=1','/dist/people.js','/server/index.js','/%70eople.js']){const r=await app.fetch(request(path),env);assert.equal(r.status,303);assert.equal(r.headers.get('location'),'/login');assert(!/PRIVATE/.test(await r.text()))}});
test('login page is generic and configuration fails closed',async()=>{const r=await app.fetch(request('/login'),env);assert.equal(r.status,200);assert(!/PRIVATE|Jacqueline|Perrin/.test(await r.text()));assert.equal((await app.fetch(request('/'),{})).status,503)});
test('correct password issues secure cookie and grants access; tampering and rotation reject it',async()=>{const r=await login('test-password-only');assert.equal(r.status,303);const set=r.headers.get('set-cookie');for(const value of ['HttpOnly','Secure','SameSite=Lax','Path=/','Max-Age=7776000'])assert(set.includes(value));const cookie=set.split(';')[0];const ok=await app.fetch(request('/people.js',{headers:{cookie}}),env);assert.equal(await ok.text(),'PRIVATE NAMES');assert(ok.headers.get('cache-control').includes('no-store'));assert.equal((await app.fetch(request('/people.js',{headers:{cookie:cookie+'x'}}),env)).status,303);assert.equal((await app.fetch(request('/',{headers:{cookie}}),{...env,FAMILY_PASSWORD_HASH:await hash('rotated')})).status,303);const expired='__Host-family=1000000000.nonce.signature';assert.equal((await app.fetch(request('/',{headers:{cookie:expired}}),env)).status,303)});
test('wrong passwords, cross-origin forms, large forms and HTTP are rejected',async()=>{assert.equal((await login('wrong')).status,401);assert.equal((await login('test-password-only',{Origin:'https://other.example'})).status,403);assert.equal((await login('x'.repeat(5000))).status,413);assert.equal((await app.fetch(new Request('http://family.example/'),env)).status,400)});
test('repeated login requests throttle; logout clears cookie and requires origin',async()=>{for(let i=0;i<10;i++)await login('wrong',{'cf-connecting-ip':'throttle-test'});assert.equal((await login('wrong',{'cf-connecting-ip':'throttle-test'})).status,429);const r=await app.fetch(request('/logout',{method:'POST',headers:{Origin:origin}}),env);assert(r.headers.get('set-cookie').includes('Max-Age=0'));assert.equal((await app.fetch(request('/logout',{method:'POST'}),env)).status,403)});
