const view=document.querySelector('#viewport'),tree=document.querySelector('#tree'),nodes=document.querySelector('#nodes'),lines=document.querySelector('#lines');
let z=1,tx=0,ty=0,expanded=new Set([1,2]),positions=new Map(),selected=3;
const openFamilies=new Set([13,14,15,3,16,17,18]);
const person=id=>people.find(p=>p.id===id),initials=p=>p.name.split(' ').map(n=>n[0]).join('');
const branchPalette={
13:['#356fba','#edf4ff'],14:['#aa7520','#fff6e4'],15:['#8055b5','#f5efff'],
3:['#32815e','#eaf6ee'],16:['#b6547c','#fff0f5'],17:['#24838b','#e9f8f9'],18:['#bc6039','#fff0e8']
};
function branchId(id){const p=person(id);if(branchPalette[id])return id;if(branchPalette[p.partner])return p.partner;return p.parents.find(id=>branchPalette[id])}
function tint(el,id){const branch=branchId(id);if(!branch)return;const [ink,fill]=branchPalette[branch];el.style.setProperty('--branch-ink',ink);el.style.setProperty('--branch-fill',fill);el.dataset.branch=String(branch)}
function transform(){tree.style.transform=`translate(${tx}px,${ty}px) scale(${z})`}
function draw(){
 nodes.replaceChildren();positions=new Map();const paths=[],dashed=[],centres=[],branchPaths={};let cursor=120;
 for(const id of [13,14,15,3,16,17,18]){const bp=branchPaths[id]=[],p=person(id),children=people.filter(c=>c.parents.includes(id)),open=openFamilies.has(id),width=open?Math.max(360,children.length*180):180,x=cursor+width/2;centres.push(x);positions.set(id,[open?x-90:x,510]);
 if(open&&p.partner){positions.set(p.partner,[x+90,510]);bp.push(`M${x-90} 510H${x+90}`);if(children.length){const xs=children.map((c,i)=>x+(i-(children.length-1)/2)*180);bp.push(`M${x} 510V690 M${xs[0]} 690H${xs.at(-1)}`);children.forEach((c,i)=>{positions.set(c.id,[xs[i],810]);bp.push(`M${xs[i]} 690V738`)})}}
 cursor+=width+30;
 }
 const root=(centres[0]+centres.at(-1))/2;positions.set(1,[root-90,220]);positions.set(2,[root+90,220]);paths.push(`M${root-90} 220H${root+90} M${root} 220V385`);
 const childXs=[13,14,15,3,16,17,18].map(id=>positions.get(id)[0]);paths.push(`M${childXs[0]} 385H${childXs.at(-1)}`);[13,14,15,3,16,17,18].forEach((id,i)=>branchPaths[id].push(`M${childXs[i]} 385V438`));
 for(const id of [1,2]){if(expanded.has(id)){const [px]=positions.get(id),xs=[px];person(id).siblings.forEach((sid,i)=>{const x=px+(id===1?-1:1)*(i+1)*180;positions.set(sid,[x,220]);xs.push(x)});dashed.push(`M${Math.min(...xs)} 130H${Math.max(...xs)}`,...xs.map(x=>`M${x} 130V148`))}}
 lines.innerHTML=`<path d="${paths.join(' ')}"/><path class="sibling" d="${dashed.join(' ')}"/>${Object.entries(branchPaths).map(([id,parts])=>`<path style="stroke:${branchPalette[id][0]};stroke-width:3" d="${parts.join(' ')}"/>`).join('')}`;
 for(const [id,[x,y]] of positions){const p=person(id),b=document.createElement('button');b.className='person'+(id===3?' grandma':'')+(id===selected&&id!==3?' selected':'');tint(b,id);b.style.left=x+'px';b.style.top=y+'px';b.setAttribute('aria-label',`${p.name}, ${p.role}`);b.innerHTML=`<span class="avatar">${initials(p)}</span><strong>${p.name}</strong>`;b.onclick=()=>{if(!suppressClick)show(id)};nodes.append(b)}
 for(const id of [1,2,13,14,15,3,16,17,18]){const rootPerson=id<=2,p=person(id),children=people.filter(c=>c.parents.includes(id)),isOpen=(rootPerson?expanded:openFamilies).has(id),b=document.createElement('button'),[x,y]=positions.get(id);b.className='branch-toggle';tint(b,id);b.style.left=x+'px';b.style.top=(y+90)+'px';b.textContent=rootPerson?(isOpen?'− Hide siblings':`+ ${p.siblings.length} siblings`):(isOpen?'− Close branch':`+ Partner${children.length?' · '+children.length+' children':''}`);b.setAttribute('aria-expanded',String(isOpen));b.onclick=()=>{if(suppressClick)return;const set=rootPerson?expanded:openFamilies;isOpen?set.delete(id):set.add(id);draw()};nodes.append(b)}
}
function reveal(id){if(positions.has(id))return;const p=person(id);if([4,5,6].includes(id))expanded.add(1);else if([7,8,9,10,11,12,19].includes(id))expanded.add(2);else if(p.partner)openFamilies.add(p.partner);else if(p.parents.length)openFamilies.add(p.parents[0]);draw()}
function focus(id){reveal(id);const [x,y]=positions.get(id);z=1;tx=innerWidth/2-x;ty=innerHeight*.46-y;selected=id;draw();transform()}
function frame(ps){const minX=Math.min(...ps.map(p=>p[0]))-105,maxX=Math.max(...ps.map(p=>p[0]))+105,minY=Math.min(...ps.map(p=>p[1]))-100,maxY=Math.max(...ps.map(p=>p[1]))+135;z=Math.max(.1,Math.min(1.1,(innerWidth-32)/(maxX-minX),(innerHeight-190)/(maxY-minY)));tx=(innerWidth-(maxX+minX)*z)/2;ty=90+(innerHeight-190-(maxY-minY)*z)/2-minY*z;transform()}
function fit(){frame([...positions.values()])}
function zoom(next,x=innerWidth/2,y=innerHeight/2){next=Math.max(.2,Math.min(2,next));tx=x-(x-tx)*next/z;ty=y-(y-ty)*next/z;z=next;transform()}
function links(ids){return ids.length?ids.map(id=>`<button class="relative-link" data-relative="${id}">${person(id).name}</button>`).join(''):'Not recorded'}
function show(id){const p=person(id),dialog=document.querySelector('#profile');selected=id;draw();document.querySelector('#details').innerHTML=`<div class="avatar profile-avatar">${initials(p)}</div><h2>${p.name}</h2><p>${p.role}</p><div class="relation"><span>Partner</span>${links(p.partner?[p.partner]:[])}</div><div class="relation"><span>Parents</span>${links(p.parents)}</div><div class="relation"><span>Siblings</span>${links(p.siblings)}</div><div class="relation"><span>Children</span>${links(people.filter(c=>c.parents.includes(id)).map(c=>c.id))}</div>`;document.querySelectorAll('[data-relative]').forEach(b=>b.onclick=()=>{dialog.close();focus(+b.dataset.relative);show(+b.dataset.relative)});if(!dialog.open)dialog.showModal()}
function results(){const q=document.querySelector('#search').value.toLowerCase().trim(),el=document.querySelector('#results');el.replaceChildren();const matches=people.filter(p=>p.name.toLowerCase().includes(q));for(const p of matches){const b=document.createElement('button');b.innerHTML=`${p.name}<small>${p.role}</small>`;b.onclick=()=>{document.querySelector('#search-dialog').close();focus(p.id)};el.append(b)}if(!matches.length)el.textContent='No relatives found.'}
document.querySelector('#search-toggle').onclick=()=>{document.querySelector('#search-dialog').showModal();results();document.querySelector('#search').focus()};document.querySelector('#search').oninput=results;document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelector('#more').onclick=()=>zoom(z*1.25);document.querySelector('#less').onclick=()=>zoom(z/1.25);document.querySelector('#fit').onclick=fit;document.querySelector('#home').onclick=()=>focus(3);
let pointers=new Map(),gesture=null,suppressClick=false;
function begin(){const p=[...pointers.values()];gesture={x:tx,y:ty,z,points:p.map(v=>({...v}))}}
view.addEventListener('pointerdown',e=>{if(e.button!==0)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});begin();suppressClick=false});
window.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const p=[...pointers.values()],g=gesture;if(p.length===1){const dx=p[0].x-g.points[0].x,dy=p[0].y-g.points[0].y;if(Math.hypot(dx,dy)>5)suppressClick=true;tx=g.x+dx;ty=g.y+dy}else if(g.points.length>=2){suppressClick=true;const a=g.points,b=p,oldDist=Math.hypot(a[1].x-a[0].x,a[1].y-a[0].y)||1,newDist=Math.hypot(b[1].x-b[0].x,b[1].y-b[0].y);z=Math.max(.2,Math.min(2,g.z*newDist/oldDist));tx=(b[0].x+b[1].x)/2-((a[0].x+a[1].x)/2-g.x)*z/g.z;ty=(b[0].y+b[1].y)/2-((a[0].y+a[1].y)/2-g.y)*z/g.z}view.classList.toggle('dragging',suppressClick);transform()});
function end(e){pointers.delete(e.pointerId);view.classList.remove('dragging');if(pointers.size)begin();else setTimeout(()=>suppressClick=false,0)}window.addEventListener('pointerup',end);window.addEventListener('pointercancel',end);
view.addEventListener('wheel',e=>{e.preventDefault();if(e.ctrlKey||e.metaKey)zoom(z*Math.exp(-e.deltaY*.01),e.clientX,e.clientY);else{tx-=e.deltaX;ty-=e.deltaY;transform()}},{passive:false});view.addEventListener('keydown',e=>{if(e.target!==view)return;const delta={ArrowLeft:[50,0],ArrowRight:[-50,0],ArrowUp:[0,50],ArrowDown:[0,-50]}[e.key];if(delta){e.preventDefault();tx+=delta[0];ty+=delta[1];transform()}else if(e.key==='+'||e.key==='=')zoom(z*1.25);else if(e.key==='-')zoom(z/1.25)});window.addEventListener('resize',fit);draw();fit();
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
